### DISCUSSION TITLE
SOK 48v 100Ah

### DISCUSSION THREAD

**Discussion by garylankford8** [syssi/esphome-pace-bms#38] [General]
Works for SOK 100ah 48v server rack with version P16S100A-1B470-4.07 after reversing TX and RX pins from as shown in the example. tx_pin: GPIO17, rx_pin: GPIO16.

To access data from multiple packs consistently using RD485 ports (next to CAN port) I did have to "daisy chain" the ports by adding RJ45 splitters to packs 1 and 2 and cables between packs. This would likely not be necessary if using the RS232 port for modbus with the other RS485 ports cabled together as for pbmstools or Solar Assistant.

I am currently using both Solar Assistant (RS232) and ESPhome-Pace-BMS (RS485).

**Comment by jingsno** [comment]
Works for my SOK 100ah 48v server rack with version "P16S100A-1B470-4.00", with a "ESP32-C3 Super Mini", and a ["MAX485" based interface module](https://www.amazon.com/YWBL-WH-RS-485-Converter-Adapter-Raspberry/dp/B07S1BN6ZK/)

I needed to add support for "flow control". Soldered "Receiver Enabled (RE)" and "Driver Enabled (DE)" together, and connected them to GPIO3.

The following changes was needed:
(I used the ESP32 code)

```
substitutions:
  tx_pin: GPIO20
  rx_pin: GPIO21
  ctrl_pin: GPIO3

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

modbus:
  - id: modbus0
    flow_control_pin: ${ctrl_pin}

```

I have a few sporadic "Modbus CRC Check failed!" messages, but everything appears to be working.

I'm using the CAN port connected to a Cerbo GX, with protocol "VICTRON_CAN", and the RS485A port connected to the ESP32-C3 with "PACE_MODBUS", at the same time. The ID switch is set as "1".

Thanks for making this!
