### DISCUSSION TITLE
Project help on communication PBMS-Tools Hylink - ESP8266 - RS232 to TTL - MQTT

### DISCUSSION THREAD

**Discussion by poweredcloud** [syssi/esphome-pace-bms#50] [Q&A]
Good morning, I apologize for my English but I write with translator.. 
I ask for help from you expert of the creation of the splendid project for reading data from this bms peace... 
I am in possession of 2 Hylink 24volt 100ah batteries that I currently read the data via Windows PC with PBMSTOOLS 2.5 via USB cable - RS232 without any problem.. 
Having installed home assistant I needed to bring data via mqtt now I haven't been able to do this thing for years now...

 I bought D1 Mini 8266 - RS232 TTL converter. but I can't load your project on the esp8266 having also installed esphome via home assistant, indeed it gives me an error... 
![Schermata 2024-08-17 alle 12 29 14](https://github.com/user-attachments/assets/6f3b23ff-aa12-41f7-8321-09f091e3ed50)
![Schermata 2024-08-18 alle 10 42 16](https://github.com/user-attachments/assets/1856a274-fab9-43e0-8c23-5dbb6fddc6fd)

![Schermata 2024-08-17 alle 12 18 57](https://github.com/user-attachments/assets/d604dba3-b9e3-4cd1-a9b3-2e9774ae0dcf)

I hope for your thanks again and to make :)

**Comment by syssi** [comment]
Pleaese press the `LOGS` button of the ESPHome node tile and provide some logs.

**Reply by poweredcloud** [reply]
Thank you very much for your reply

![Schermata 2024-08-18 alle 10 46 42](https://github.com/user-attachments/assets/d40d06b0-9b15-4fa9-9054-16d98b49a496)
![Schermata 2024-08-18 alle 12 33 53](https://github.com/user-attachments/assets/8e40db77-01bc-4436-9ac9-21a066958ae8)

**Reply by syssi** [reply]
It looks like your YAML isn't correct. Could you provide your YAML as plaintext (press the `EDIT` button + copy&paste).

**Reply by poweredcloud** [reply]
I copied your work

# Install esphome
pip3 install esphome

# Clone this project
git clone https://github.com/syssi/esphome-pace-bms.git
cd esphome-pace-bms

# Create a secrets.yaml containing some setup specific secrets
cat > secrets.yaml <<EOF
wifi_ssid: MY_WIFI_SSID
wifi_password: MY_WIFI_PASSWORD

mqtt_host: MY_MQTT_HOST
mqtt_username: MY_MQTT_USERNAME
mqtt_password: MY_MQTT_PASSWORD
EOF

# Validate the configuration, create a binary, upload it, and start logs
# If you use a esp8266 run the esp8266-examle.yaml
esphome run esp32-example.yaml

**Comment by poweredcloud** [comment]
![Schermata 2024-08-18 alle 10 45 55](https://github.com/user-attachments/assets/4df5c9c5-7b1d-4c2a-9441-eae389e17759)

**Reply by syssi** [reply]
There is a misunderstanding how to setup a ESPHome node. This is the correct YAML:

https://raw.githubusercontent.com/syssi/esphome-pace-bms/main/esp8266-example.yaml

**Reply by poweredcloud** [reply]
i loaded your yaml seems to have loaded it, but i still don't see mqtt

[logs_d1_run.txt](https://github.com/user-attachments/files/16648151/logs_d1_run.txt)

**Reply by poweredcloud** [reply]
I apologize for the inconsistency. 

I think I have successfully uploaded your file but I still can't see any link in my MQTT server the device does not send any type of data...

 I turn you the yam file if anything when you have time take a look at me... 
![Schermata 2024-08-18 alle 15 01 54](https://github.com/user-attachments/assets/d2913357-8513-49f8-beda-4c18e41850af)

Of course I have to connect RS 232 not 485?

**Reply by syssi** [reply]
The node crashs while doing the setup because it's "out of memory" (OOM):

```
[13:08:57]--------------- CUT HERE FOR EXCEPTION DECODER ---------------
[13:08:57]
[13:08:57]Unhandled C++ exception: OOM
[13:08:57]
[13:08:57]>>>stack>>>
WARNING Found stack trace! Trying to decode it
[13:08:57]
[13:08:57]ctx: cont
[13:08:57]sp: 3ffffdf0 end: 3fffffd0 offset: 0010
[13:08:57]3ffffe00:  00000000 00000020 000000b0 40224d44  
WARNING Decoded 0x40224d44: operator new(unsigned int)
[13:08:57]3ffffe10:  00000000 3fff2e20 3fff28d8 4021a1cb  
WARNING Decoded 0x4021a1cb: setup
[13:08:57]3ffffe20:  00000001 00000000 00000000 feefeffe  
[13:08:57]3ffffe30:  3fffbebc 3fff87a0 40229074 40212f58  
WARNING Decoded 0x40229074: std::_Function_handler<esphome::optional<float> (esphome::modbus_controller::ModbusNumber*, float, std::vector<unsigned short, std::allocator<unsigned short> >&), setup::{lambda(esphome::modbus_controller::ModbusNumber*, float, std::vector<unsigned short, std::allocator<unsigned short> >&)#24}>::_M_manager(std::_Any_data&, std::_Function_handler<esphome::optional<float> (esphome::modbus_controller::ModbusNumber*, float, std::vector<unsigned short, std::allocator<unsigned short> >&), setup::{lambda(esphome::modbus_controller::ModbusNumber*, float, std::vector<unsigned short, std::allocator<unsigned short> >&)#24}> const&, std::_Manager_operation) at main.cpp
WARNING Decoded 0x40212f58: std::_Function_handler<esphome::optional<float> (esphome::modbus_controller::ModbusNumber*, float, std::vector<unsigned short, std::allocator<unsigned short> >&), setup::{lambda(esphome::modbus_controller::ModbusNumber*, float, std::vector<unsigned short, std::allocator<unsigned short> >&)#24}>::_M_invoke(std::_Any_data const&, esphome::modbus_controller::ModbusNumber*&&, float&&, std::vector<unsigned short, std::allocator<unsigned short> >&) at main.cpp
``` 

The ESP8266 isn't able to handle all available sensors. Let's start with this simple YAML configuration (we will add more sensors later):

```yaml
substitutions:
  name: pace-bms
  device_description: "Monitor and control a PACE BMS via RS485 (Modbus)"
  tx_pin: GPIO4
  rx_pin: GPIO5
  flow_control_pin: GPIO12

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  project:
    name: "syssi.esphome-pace-bms"
    version: 2.0.0

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  platform: esphome

logger:
  level: DEBUG

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_username
  password: !secret mqtt_password
  id: mqtt_client

# api:

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin}
    rx_pin: ${rx_pin}
    debug:
      direction: BOTH
      dummy_receiver: false

modbus:
  - id: modbus0
    uart_id: uart_0
    flow_control_pin: ${flow_control_pin}
    send_wait_time: 200ms

modbus_controller:
  - id: bms0
    # Slave address 0x01
    address: 0x01
    modbus_id: modbus0
    command_throttle: 200ms
    update_interval: 10s

sensor:
  #   0  Current                               2 byte   R   int16  10mA (Positive: chargingm Negative: discharging)
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "${name} current"
    address: 0
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "A"
    device_class: current
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  #   1  Voltage of pack                       2 byte   R  uint16  10mV
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "${name} total voltage"
    address: 1
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "${name} power"
    address: 0
    register_type: holding
    value_type: U_WORD
    register_count: 2
    response_size: 4
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 2
    lambda: |-
      if (data.size() < 4) {
        return NAN;
      }
      float current = (int16_t)(data[0] << 8 | data[1] << 0);
      float total_voltage = (uint16_t)(data[2] << 8 | data[3] << 0);
      return current * total_voltage * 0.0001f;

  #   2  State of charge                       2 byte   R   uint8  % (0-100%)
  - platform: modbus_controller
    modbus_controller_id: bms0
    name: "${name} state of charge"
    address: 2
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    accuracy_decimals: 0
```

Our goal is to proof your BMS is able to communicate using the Modbus protocol on the RS232 port.
